image: node:latest

stages:
  - build
  - test
  - deploy

# the configuration includes a cache that specifies files
# that should be saved for later to be used between runs or stages.
cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  tags:
    - my-tag
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  tags:
    - my-tag
  script:
    - yarn test

#Production stage
deploying:
  stage: deploy
  before_script:
    #generate ssh key
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash .gitlab-deploy.sh
  environment:
    name: production
    url: http://c-bound.io
  when: manual
