image: node:latest

stages:
  - build
  - test
  - deploy

# the configuration includes a cache that specifies files
# that should be saved for later to be used between runs or stages.
cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  tags:
    - my-tag
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  tags:
    - my-tag
  script:
    - yarn test

#Production stage
deploying:
  stage: deploy
  tags:
    - my-tag
  script:
    # 최대 요청 대기시간은 5분
    - curl --connect-timeout 300 https://c-bound.io/cmd/deploy
  environment:
    name: production
    url: http://c-bound.io
  when: manual
